export enum GroupBoardHistoryTypes {
  'CREATE_COLUMN' = 0,
  'DROP_COLUMN' = 1,
  'ADD_NEW_CARD_TO_COLUMN' = 2,
  'DROP_CARD_FROM_COLUMN' = 3,
  'MOVE_CARD_FROM_COLUMN_TO_COLUMN' = 4,
  'ASSIGN_MEMBER_TO_CARD' = 5,
  'UNASSIGN_MEMBER_FROM_CARD' = 6,
  'FINISH_ASSIGNED_TASK_FROM_CARD' = 7,
}
